steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/zking2000/gcp_devops.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pm-instance/my-image', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pm-instance/my-image']

